### ISSUE TITLE
Handle AP Number request?

### ISSUE THREAD

**Issue by jeffw16** [jbman223/EarlyAP#1]
Hello,
Glad to see this service up and running! Hopefully DigitalOcean's SF IPs are not blacklisted by CollegeBoard…

I was wondering how the service will input our AP number in case that is requested by CB upon login. I can't seem to find anything in the code that would handle that. Also glad that it's written in PHP 😛 Thanks!

**Comment by jbman223** [comment]
@jeffw16 Hey, thanks for the suggestion. Do you have any ideas for handling the AP number requests? The reason I had not accounted for them is because I never had to enter mine, so I couldn't grab the URL schema that makes entering the number necessary.

**Comment by jbman223** [comment]
@jeffw16 It appears that this year AP Number support is in the pipeline - it should be complete within the next couple of days.

**Comment by jeffw16** [comment]
Hey, sorry to leave you hanging. I never was able to figure out how to handle the params, but this year the number one reason why EarlyScores could not check was because the users did not yet accept the AP Terms and Conditions. I was able to download a copy of that page while manually checking someone's score. Any ideas on how to track the params needed to handle that? The 2nd most common reason would be AP numbers (usually need AP number, address, city, state, and ZIP code), and the least common issue is a missing score.
