### ISSUE TITLE
Unable to fetch my score

### ISSUE THREAD

**Issue by MaxLeiter** [jbman223/EarlyAP#6]
While the client (DOM) just says "Securely decrypting scores...", console shows this Object:
```

elapsedTime: "Score fetched in 2.044741153717041 seconds."
endtime: 1499281567.800162
salt:"<salt>"
starttime: 1499281565.755421
status: -4
```
I believe `-4` means I haven't accepted the terms and conditions (but I have).

Help appreciated.

**Comment by jbman223** [comment]
Try using the hosted proxy. https://earlyscores.com/proxy.html

**Comment by jbman223** [comment]
TOS acceptance is possible with the 2018 application. Thanks for the report.
