### ISSUE TITLE
User Name Upon receiving scores

### ISSUE THREAD

**Issue by refcell** [jbman223/EarlyAP#9]
Hello Jacob Buckheit,

My school, and I am sure others, need the persons credentials above your scores so they can be verified as your own. Would it be possible to add this as a feature?

Regards,
Andreas

**Comment by BK1031** [comment]
If you want to use actually use your scores for credit purposes, I would recommend just waiting for CollegeBoard's official score report. I would think that EarlyScores is mainly just for the student to see their scores early out of curiosity.

**Comment by jbman223** [comment]
EarlyScores score reports are not meant to be used officially, so this feature won't be implemented into the API.
